CATEGORIA_AIRE_ACONDICIONADO = 'aires-acondicionados'
CATEGORIA_NOTEBOOK = 'notebooks'
CATEGORIA_TELEVISOR = 'televisores'
CATEGORIA_CELULAR = 'celulares'
CATEGORIA_HELADERA = 'heladeras'
CATEGORIA_ZAPATILLA = 'zapatillas'
CATEGORIA_LAVARROPAS = 'lavarropas'
CATEGORIA_TABLET = 'tablets'
CATEGORIA_PC = 'pcs'
CATEGORIA_MICROONDAS = 'microondas'
CATEGORIA_HORNO = 'hornos'
CATEGORIA_COCINA = 'cocinas'
CATEGORIA_TERMOTANQUE = 'termotanques'
CATEGORIA_CALEFON = 'calefones'
CATEGORIA_VENTILADOR = 'ventiladores'
CATEGORIA_GAMER = 'gamer'
CATEGORIA_MODA = 'moda'
CATEGORIA_BELLEZA = 'belleza'
CATEGORIA_TECNOLOGIA = 'tecnologia'


NOMBRES_CATEGORIAS = [
    CATEGORIA_TELEVISOR,
    CATEGORIA_CELULAR,
    CATEGORIA_ZAPATILLA,
    CATEGORIA_AIRE_ACONDICIONADO,
    CATEGORIA_NOTEBOOK,
    CATEGORIA_HELADERA,
    CATEGORIA_LAVARROPAS,
    CATEGORIA_TABLET,
    CATEGORIA_PC,
    CATEGORIA_MICROONDAS,
    CATEGORIA_HORNO,
    CATEGORIA_COCINA,
    CATEGORIA_TERMOTANQUE,
    CATEGORIA_CALEFON,
    CATEGORIA_VENTILADOR,
    CATEGORIA_GAMER,
    CATEGORIA_MODA,
    CATEGORIA_BELLEZA,
    CATEGORIA_TECNOLOGIA,
]
